sudo: no
language: python
python:
  - 2.7
install:
  - pip install -r requirements/production.txt
  - pip install coveralls
script:
  - cd djangomx
  - coverage run manage.py test
after_success:
  coveralls
