sudo: no
language: python
python:
  - 2.7
install:
  - pip install -r requirements/development.txt
  - pip install coveralls
script:
  - cd djangomx
  - nosetests --with-coverage --cover-package=accounts,blog --verbosity=1
after_success:
  - coveralls
